### PR TITLE
Specialize boost::is_integral for char8_t when available. Fixes #175.

### LINKED ISSUE #175: boost::is_integral<char8_t>::value is false
... but should be true.

### PR DESCRIPTION
**Pull request by pdimov**

### CODE REVIEW

**Comment by jzmaddock** [comment]
Failing tests are unrelated and inscrutable so merging.

**Comment by pdimov** [comment]
The XCode failures seem to mostly be caused by a missing but used `std::declval`, although there might be something else as well.

GCC 4.4 -std=c++0x fails some "tricky" tests because of who knows why.

**Comment by jzmaddock** [comment]
I know, but nothing has changed around here, so I'm perplexed.

**Comment by pdimov** [comment]
The new run has these
```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
```
which is odd. And sure enough, the old runs that succeed such as [this one](https://drone.cpp.al/boostorg/type_traits/44/30/2) use libc++
```
libc++ version 5000
    _LIBCPP_VERSION                         =5000
```
but the [failing run](https://drone.cpp.al/boostorg/type_traits/55/30/2) uses libstdc++:
```
GNU libstdc++ version 20070719
    __GLIBCXX__                             =20070719
    _GLIBCXX_USE_WCHAR_T                    =1
    _GLIBCXX_USE_LONG_LONG                  =1
    _GLIBCXX_USE_C99_MATH                   =1
    _GLIBCXX_USE_C99                        =1
    _GLIBCXX_SYMVER                         =1
    _GLIBCXX_HOSTED                         =1
```
This is either caused by a change in the images or by a change in Boost.CI - depending on which of these installs GCC.

@sdarwin @Flamefire

**Comment by pdimov** [comment]
The GCC 4.4 failures
```
./boost/config/stdlib/libstdcpp3.hpp:262: error: "_GLIBCXX_USE_DEPRECATED" is not defined
```
are probably caused by https://github.com/boostorg/type_traits/commit/d71524a79958942c3a9cbd93099b5180c490a68a which adds
```
   <toolset>gcc:<cxxflags>-Wundef
```
to test/Jamfile.v2.

**Comment by pdimov** [comment]
No idea whether the use of `_GLIBCXX_USE_DEPRECATED` at https://github.com/boostorg/config/blob/2543ff139707a32cc421b62c9d65bb4d9c965b3e/include/boost/config/stdlib/libstdcpp3.hpp#L262 is correct or not for GCC 4.4.

**Comment by Flamefire** [comment]
> The GCC 4.4 failures
> 
> ```
> ./boost/config/stdlib/libstdcpp3.hpp:262: error: "_GLIBCXX_USE_DEPRECATED" is not defined
> ```
> 
> are probably caused by [d71524a](https://github.com/boostorg/type_traits/commit/d71524a79958942c3a9cbd93099b5180c490a68a) which adds


Correct although confusing: There is a check `if BOOST_LIBSTDCXX_VERSION < 40600` before so the define shouldn't be checked. Anyway opened a PR to fix that by checking if it is define first.
